'''
Created on 07.11.2017

@author: bsmoehring
'''


class osm(object):
    '''
    This class aims to store required strings to parse OSM data
    '''
    Id = 'id'
    Osm = 'osm'
    Node = 'node'
    Way = 'way'
    Relation = 'relation'
    Ref = 'ref'
    NodeRef = 'nd'
    Lat = 'lat'
    Lon = 'lon'
    Bounds = 'bounds'
    MinLat = 'minlat'
    MinLon = 'minlon'
    MaxLat = 'maxlat'
    MaxLon = 'maxlon'
    Level = 'level'
    Member = 'member'
    Type = 'type'
    Role = 'role'
    Outer = 'outer'
    Inner = 'inner'
    Key = 'k'
    Value = 'v'
    Tag = 'tag'
    Width = 'width'

class jps(object):
    '''
    This class aims to store required strings for the jps input files
    '''
    JuPedSim = 'jupedsim'
    Geometry = 'geometry'
    Rooms = 'rooms'
    Room = 'room'
    Subroom = 'subroom'
    Polygon = 'polygon'
    Vertex = 'vertex'
    Id = 'id'
    Caption = 'caption'
    PX = 'px'
    PY = 'py'
    Wall = 'wall'
    OriginalId = 'originalId'
    Transitions = 'transitions'
    Transition = 'transition'
    Crossing = 'crossing'
    Crossings = 'crossings'
    Type = 'type'
    Room1 = 'room1_id'
    Subroom1 = 'subroom1_id'
    Room2 = 'room2_id'
    Subroom2 = 'subroom2_id'
    OutsideTransitionRef = '-1'
    Goal = 'goal'
    Class = 'class'

